##### [ 데이터 전처리 -1 : 인코딩 & 디코딩 ]
- 범주형 => 수치형 : 인코딩(Encoding)
- 수치형 => 범주형 : 디코딩(Decoding)
- scikit-learn의 preprocessing 서브 패키지에 제공
    * LabelEncoder : 타겟/라벨/클래스 컬럼 전용 => 0 ~ 클래스 -1

    * OrdinalEncoder : 범주형 피쳐에 대한 인코딩 => 정수값 변환. 순서가 중요한 피쳐 
                      (예 : 만족도, 석차, 등급, ...)
    * OneHotEncoder : 범주형 피쳐에 대한 인코딩 => 값의 의미가 없고 데이터의 의미가 중요한 피쳐 
                      (예 : 성별, 혈액형, 도시명, ...)
    * TargetEncoder : OneHotEncoder에 대한 대안. 타겟/라벨/클래스 컬럼의 데이터 타입에 따른 인코딩 진행 
                      (예: 이진, 다중, 수치, 연속 ...)

[1] LableEncoder <hr>

In [37]:
## 관련 모듈 로딩
from sklearn.preprocessing import LabelEncoder

## 학습 진행 : 인코딩 대상 적용
lencoder = LabelEncoder()
lencoder.fit(["paris", "paris", "tokyo", "amsterdam"])

## 모델 파라미터 확인
print(f'classes : {lencoder.classes_}, {lencoder.get_params}')

## 변형
encoding = lencoder.transform(['paris', 'paris', 'tokyo'])
print('encoding : ', encoding)

## 복원/ 디코딩 => ndarray
lencoder.inverse_transform(encoding)

classes : ['amsterdam' 'paris' 'tokyo'], <bound method BaseEstimator.get_params of LabelEncoder()>
encoding :  [1 1 2]


array(['paris', 'paris', 'tokyo'], dtype='<U9')

In [38]:
## 관련 모듈 로딩
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

## 테스트용 데이터
data = pd.DataFrame({'gender' : ['F', 'F', 'M', 'F', 'M', 'UN']})

## 인스턴스 생성
ordEncoder = OrdinalEncoder()
ordEncoder.fit(data)

## 설정된 인코딩 정보 확인
print(f'feature_names_in_ : {ordEncoder.feature_names_in_}')
print(f'categories_      : {ordEncoder.categories_}')
print(f'n_features_in_ : {ordEncoder.n_features_in_}')

## 인코딩 진행
encoding = ordEncoder.transform(data)
print('인코딩 결과 \n', encoding)

print() 

## 복원/디코딩
print('복원/디코딩 결과\n', ordEncoder.inverse_transform(encoding))


feature_names_in_ : ['gender']
categories_      : [array(['F', 'M', 'UN'], dtype=object)]
n_features_in_ : 1
인코딩 결과 
 [[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [2.]]

복원/디코딩 결과
 [['F']
 ['F']
 ['M']
 ['F']
 ['M']
 ['UN']]


[3] OnHotEncoder <hr>

In [39]:
## 관련 모듈 로딩
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

## 테스트용 데이터
data = pd.DataFrame({'gender' : ['F', 'F', 'M', 'F', 'M', 'UN']})

## 인스턴스 생성
ohEncoder = OneHotEncoder(sparse_output=False)
ohEncoder.fit(data)

## 설정된 인코딩 정보 확인
print(f'categories_       : {ohEncoder.categories_}')
print(f'feature_names_in_ : {ohEncoder.feature_names_in_}')

## 인코딩 진행
encoding = ohEncoder.transform(data)
print('인코딩 결과 \n', encoding)

print() 

## 복원/디코딩
print('복원/디코딩 결과\n', ohEncoder.inverse_transform(encoding))


categories_       : [array(['F', 'M', 'UN'], dtype=object)]
feature_names_in_ : ['gender']
인코딩 결과 
 [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

복원/디코딩 결과
 [['F']
 ['F']
 ['M']
 ['F']
 ['M']
 ['UN']]


[4] TargetEncoder <hr>

In [40]:
## 관련 모듈 로딩
from sklearn.preprocessing import TargetEncoder

## 테스트 데이터
df = pd. DataFrame({"city": ["Seoul", "Busan","Seoul", "Daegu", "Busan", "Seoul", "Incheon", "Daegu", "Busan", "Seoul"],
                    "age": (25, 32, 41, 23, 37, 29, 33, 45, 28, 48),
                    "У":  [2, 0, 1, 0, 0, 1, 1, 8, 0, 1] })

display(df)
                   

city  age  У
0    Seoul   25  2
1    Busan   32  0
2    Seoul   41  1
3    Daegu   23  0
4    Busan   37  0
5    Seoul   29  1
6  Incheon   33  1
7    Daegu   45  8
8    Busan   28  0
9    Seoul   48  1

In [41]:
import numpy as np
## 피쳐 컬럼 : city, ate/ 타겟 컬럼 : y
## 피쳐 컬럼 중 텍스트 데이터의 city ====> 수치화 즉, 인코딩

## -> OneHot
ohEncoder = OneHotEncoder(sparse_output=False)
cityArr = ohEncoder.fit_transform(df[['city']])
ageArr = df[df.columns[1:-1]].values

np.concatenate((cityArr, ageArr), axis=1)

array([[ 0.,  0.,  0.,  1., 25.],
       [ 1.,  0.,  0.,  0., 32.],
       [ 0.,  0.,  0.,  1., 41.],
       [ 0.,  1.,  0.,  0., 23.],
       [ 1.,  0.,  0.,  0., 37.],
       [ 0.,  0.,  0.,  1., 29.],
       [ 0.,  0.,  1.,  0., 33.],
       [ 0.,  1.,  0.,  0., 45.],
       [ 1.,  0.,  0.,  0., 28.],
       [ 0.,  0.,  0.,  1., 48.]])

In [42]:
display(cityArr)
df['city'] = cityArr

df

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

city  age  У
0   0.0   25  2
1   1.0   32  0
2   0.0   41  1
3   0.0   23  0
4   1.0   37  0
5   0.0   29  1
6   0.0   33  1
7   0.0   45  8
8   1.0   28  0
9   0.0   48  1