### [ Tensor 객체 생성 ]
- 일반 텐서 : torch tensor(), seros(), ones(), full(), eye()
- 난수 텐서 : torch.rand(), randn(), randint()
- 텐서 생성자 : torch.FloatTensor(), IntTensor(), BoolTensor(), Tensor()

In [1]:
## 모듈 로딩
import torch

In [6]:
## ===============================================================
## 기능 : 텐서 정보 출력
## 이름 : printInfo
## 매개변수 : tensor
## 반환결과 : 없음
## ===============================================================
def printInfo(tensor, tname):
    print(f'======[{tname} 정보]')
    print(f"- shape : {tensor.shape}")
    print(f"- ndim : {tensor.ndim}")
    print(f"- dtype : {tensor.dtype}")
    print(f"- device : {tensor.device}")
    print(f"- data : \n{tensor.data}")
    

In [10]:
## ===============================================================
## 텐서 생성하기 - 1.일반적인 방법
## ===============================================================
t0 = torch.tensor(10, dtype=torch.int8)
t1 = torch.tensor([11,22])
t2 = torch.tensor([[11,22,33],[44,55,66]])
t3 = torch.tensor([[[11,22],[33,44]],[[55,66],[77,88]]])

printInfo(t3, "t3")

======[t3 정보]
- shape : torch.Size([2, 2, 2])
- ndim : 3
- dtype : torch.int64
- device : cpu
- data : 
tensor([[[11, 22],
         [33, 44]],

        [[55, 66],
         [77, 88]]])


In [13]:
## ===============================================================
## 텐서 생성하기 - 1.일반적인 방법 + 위치 설정
## ===============================================================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

t0 = torch.tensor(10, dtype=torch.int8, device = DEVICE)
t1 = torch.tensor([11,22])
t2 = torch.tensor([[11,22,33],[44,55,66]])
t3 = torch.tensor([[[11,22],[33,44]],[[55,66],[77,88]]], device = DEVICE)

printInfo(t0, "t0")
printInfo(t1, "t1")
printInfo(t2, "t2")
printInfo(t3, "t3")


======[t0 정보]
- shape : torch.Size([])
- ndim : 0
- dtype : torch.int8
- device : cuda:0
- data : 
10
======[t1 정보]
- shape : torch.Size([2])
- ndim : 1
- dtype : torch.int64
- device : cpu
- data : 
tensor([11, 22])
======[t2 정보]
- shape : torch.Size([2, 3])
- ndim : 2
- dtype : torch.int64
- device : cpu
- data : 
tensor([[11, 22, 33],
        [44, 55, 66]])
======[t3 정보]
- shape : torch.Size([2, 2, 2])
- ndim : 3
- dtype : torch.int64
- device : cuda:0
- data : 
tensor([[[11, 22],
         [33, 44]],

        [[55, 66],
         [77, 88]]], device='cuda:0')


In [14]:
## ===============================================================
## 텐서 생성하기 - 1.일반적인 방법 + 위치 설정
## ===============================================================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

t0 = torch.tensor(10, dtype=torch.int8, device = DEVICE)
t1 = torch.tensor([11,22])
t2 = torch.tensor([[11,22,33],[44,55,66]])
t3 = torch.tensor([[[11,22],[33,44]],[[55,66],[77,88]]], device = DEVICE)

printInfo(t0, "t0")
printInfo(t1, "t1")
printInfo(t2, "t2")
printInfo(t3, "t3")


======[t0 정보]
- shape : torch.Size([])
- ndim : 0
- dtype : torch.int8
- device : cuda:0
- data : 
10
======[t1 정보]
- shape : torch.Size([2])
- ndim : 1
- dtype : torch.int64
- device : cpu
- data : 
tensor([11, 22])
======[t2 정보]
- shape : torch.Size([2, 3])
- ndim : 2
- dtype : torch.int64
- device : cpu
- data : 
tensor([[11, 22, 33],
        [44, 55, 66]])
======[t3 정보]
- shape : torch.Size([2, 2, 2])
- ndim : 3
- dtype : torch.int64
- device : cuda:0
- data : 
tensor([[[11, 22],
         [33, 44]],

        [[55, 66],
         [77, 88]]], device='cuda:0')


In [18]:
## ===============================================================
## 텐서 생성하기 - 1.일반적인 방법 
## ===============================================================
import pandas as pd

## dataframe, series 객체 생성
df = pd.DataFrame([[11,22,33], [44, 55, 66]])
sr = df[0]

## dataframe, series -> tensor 변환
torch.tensor(df.values)
torch.tensor(sr)



tensor([11, 44])