# 제목
## 제목
### 제목
- 현재 셀만 실행 : ctrl + enter 
- 현재 셀 실행 후 아래 셀 없으면 셀 추가 후 이동 => shift + enter
- 패키지 설치
    * !pip install 패키지명 / %pip isntall 패키지명
    * conda 설치 명령어 미지원 ==> Termianl 실행 후 본인 가상환경에서 설치
    * pip 설치만 지원하는 패키지는 pip로 설치
    * 그 외는 conda 로 설치하는 것이 충돌을 예방할 수 있음

In [14]:
import pandas as pd

In [15]:
## ----------------------------------------------------------------------
## -> Series 인스턴스의 속성 읽기
## ----------------------------------------------------------------------
def print_DF(df):
    print("\n--------------속성 읽기 -------------------")
    print('인덱스 :',df.index)
    print('컬럼즈 :',df.columns)
    print(f'데이터 :\n{df.values}, {type(df.values)}')
    print(f'형  태 : {df.shape}') ## 1차원으로 원소 수 반환
    print(f'차  원 : {df.ndim}') ## 1차원
    print(f'타  입 : \n{df.dtypes}')

In [16]:
## ----------------------------------------------------------------------
## -> 데이터 준비
## ----------------------------------------------------------------------
jumsu = [[99, 77, 55], [78,12,33], [98,23,91]]
idx = ['0번', '1번', '2번']
cols = ['국어','체육', '과학']


In [17]:
## ----------------------------------------------------------------------
## -> Series로 변환 저장
## ----------------------------------------------------------------------
## -> 데이터, 행인덱스
df1 = pd.DataFrame(jumsu, idx)

## -> 데이터, 행인덱스, 열인덱스
df2 = pd.DataFrame(jumsu,idx,cols)

## -> 데이터, 행인덱스, 열인덱스, 타입즈
df3 = pd.DataFrame(jumsu,idx,cols,dtype='int8')

In [18]:
## ----------------------------------------------------------------------
## -> List와 Series 데이터 표현/저장 방식 비교
## ----------------------------------------------------------------------
print_DF(df1)
print()
print_DF(df2)
print()
print_DF(df3)




--------------속성 읽기 -------------------
인덱스 : Index(['0번', '1번', '2번'], dtype='object')
컬럼즈 : RangeIndex(start=0, stop=3, step=1)
데이터 :
[[99 77 55]
 [78 12 33]
 [98 23 91]], <class 'numpy.ndarray'>
형  태 : (3, 3)
차  원 : 2
타  입 : 
0    int64
1    int64
2    int64
dtype: object


--------------속성 읽기 -------------------
인덱스 : Index(['0번', '1번', '2번'], dtype='object')
컬럼즈 : Index(['국어', '체육', '과학'], dtype='object')
데이터 :
[[99 77 55]
 [78 12 33]
 [98 23 91]], <class 'numpy.ndarray'>
형  태 : (3, 3)
차  원 : 2
타  입 : 
국어    int64
체육    int64
과학    int64
dtype: object


--------------속성 읽기 -------------------
인덱스 : Index(['0번', '1번', '2번'], dtype='object')
컬럼즈 : Index(['국어', '체육', '과학'], dtype='object')
데이터 :
[[99 77 55]
 [78 12 33]
 [98 23 91]], <class 'numpy.ndarray'>
형  태 : (3, 3)
차  원 : 2
타  입 : 
국어    int8
체육    int8
과학    int8
dtype: object
