##### [Numpy - Array 생성 ]

In [2]:
## 모듈로딩
import numpy as np

In [10]:
## ============================================
## 빈 array 객체 생성
## ============================================
a1 = np.empty((3,4))
a2 = np.empty(2)
a2

array([0.00000000e+000, 2.12199579e-314])

In [13]:
## 초기화 => 갑 넣기
a1.fill(0)

a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
## ============================================
## 0으로 채운 array 객체 생성
## ===========================================
## => float64 기본
a1 = np.zeros((2,3))
print(a1.dtype, a1, sep='\n')


## => int8
a1 = np.zeros((2,3), dtype=np.int8)
print(a1.dtype, a1, sep='\n')

## => bool
a1 = np.zeros((2,3), dtype=np.bool)
print(a1.dtype, a1, sep='\n')

float64
[[0. 0. 0.]
 [0. 0. 0.]]
int8
[[0 0 0]
 [0 0 0]]
bool
[[False False False]
 [False False False]]


In [17]:
## ============================================
## 1으로 채운 array 객체 생성
## ===========================================
## => float64 기본
a1 = np.ones((2,3))
print(a1.dtype, a1, sep='\n')


## => int8
a1 = np.ones((2,3), dtype=np.int8)
print(a1.dtype, a1, sep='\n')

## => bool
a1 = np.ones((2,3), dtype=np.bool)
print(a1.dtype, a1, sep='\n')

float64
[[1. 1. 1.]
 [1. 1. 1.]]
int8
[[1 1 1]
 [1 1 1]]
bool
[[ True  True  True]
 [ True  True  True]]
