##### [Numpy - 형태 변경]
- 1차원 -> n차원, n차원 -> 1차원 : 원소 개수 변경 안됨!!

- 1차원 <=> n차원
    + np.reshape()함수, ndarray.reshape() 메서드
    + np.resize() 함수, ndarray.resize() 메서드
    
- n차원 => 1차원
    + np.flatten()함수, ndarray.flatten() 메서드
    + np.ravel() 함수, ndarray.ravel() 메서드

In [2]:
## 모듈 로딩
import numpy as np

In [3]:
## 임의 데이터 ndarray 객체 생성
a = np.arange(11, 34, 2)
print(a.shape, a.dtype, a, sep="\n")

(12,)
int64
[11 13 15 17 19 21 23 25 27 29 31 33]


In [4]:
## ===================================
## 다양한 형태(shape) 변경
## ===================================
## 1D (12,) => 2D : (1,12), (2,6), (3,4), (4,3), (6,2) ,(12,1)
d2 = a.reshape((3,4))

print("변경후 :", d2.shape)

d2 = a.reshape((3,-1))
print("변경후 :", d2.shape)

d2 = a.reshape((6,-1))
print("변경후 :", d2.shape)


변경후 : (3, 4)
변경후 : (3, 4)
변경후 : (6, 2)


In [5]:
## ===================================
## 다양한 형태(shape) 변경 / 원소 개수 변경 가능
## ===================================
## 1D (12,) => 2D : (1,12), (2,6), (3,4), (4,3), (6,2) ,(12,1)

d3 = np.resize(a, (1,6))
print("변경후 :", d3.shape)

print(d2)
print(d3)




변경후 : (1, 6)
[[11 13]
 [15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]]
[[11 13 15 17 19 21]]


In [6]:
## ===================================
## 다양한 형태(shape) 변경 / n -> 1차원
## ===================================
a = np.array([[[11,12], [13,14], [15,16]]])
print(a.shape, a, sep='\n')

a1 = a.reshape(-1)
print(a1.shape, a1, sep='\n')

## 방법1) reshape(), resize()
## -> resize() : 원본 적용 0, -1 사용 불가
a.resize(6)
print(a.shape, a, sep='\n')


(1, 3, 2)
[[[11 12]
  [13 14]
  [15 16]]]
(6,)
[11 12 13 14 15 16]
(6,)
[11 12 13 14 15 16]


In [10]:
## 방법2) flatten()
## -> flatten() : 복사본 생성 후 1차원 변환. 속도가 상대적으로 느림
a = np.array([[[11,12], [13,14], [15,16]]])
print('원본 => ', a.shape, a, sep="\n")
print()

a1 = a.flatten()
print('1차원변형 => ', a1)
print()

a[0][0][0] = 77 
print('원본 a => ', a)
print('원본 a1 => ', a1)



원본 => 
(1, 3, 2)
[[[11 12]
  [13 14]
  [15 16]]]

1차원변형 =>  [11 12 13 14 15 16]

원본 a =>  [[[77 12]
  [13 14]
  [15 16]]]
원본 a1 =>  [11 12 13 14 15 16]


In [ ]:
## 방법3) revel()
## -> revel() : 원본 공유해서 1차원 변환
a = np.array([[[11,12], [13,14], [15,16]]])
print('원본 => ', a.shape, a, sep="\n")
print()

a1 = a.flatten()
print('1차원변형 => ', a1)
print()

a[0][0][0] = 77 
print('원본 a => ', a)
print('원본 a1 => ', a1)

