##### [Numpy - 형태 변경]

- ndarray의 축확인 => shape 속성
    + 예: shape(3,2,1) => 0번축 3, 1번축 2, 2번축 1
    + 예: shape(1,1,2,3) => 0번축 1, 1번축 1, 2번축 2, 3번축 3

In [30]:
## 모듈 로딩
import numpy as np

In [31]:
## 임의 데이터 ndarray 객체 생성
a = np.ones((2,2,3))
print(a.shape, a.dtype, a, sep="\n")

(2, 2, 3)
float64
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [32]:
## ===================================
## 축변경 : T & transpose
## ===================================
## ndarray의 속성 T
a1 = a.T
print('a.T : ','\n', a1)
print(a1.shape)

print() 

## ndarray의 메서드 transpose()
## -> (2,2,3) -> (2,0,1)
at = np.transpose(a, (0,2,1))
print("transpose : ", "\n", at)
print(at.shape)

a.T :  
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
(3, 2, 2)

transpose :  
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(2, 3, 2)


In [33]:
## ===================================
## 다양한 형태(shape) 변경 / 원소 개수 변경 가능
## ===================================
## 1D (12,) => 2D : (1,12), (2,6), (3,4), (4,3), (6,2) ,(12,1)

d3 = np.resize(a, (1,6))
print("변경후 :", d3.shape)

print(d2)
print(d3)




변경후 : (1, 6)


NameError: name 'd2' is not defined

In [ ]:
## ===================================
## 다양한 형태(shape) 변경 / n -> 1차원
## ===================================
a = np.array([[[11,12], [13,14], [15,16]]])
print(a.shape, a, sep='\n')

a1 = a.reshape(-1)
print(a1.shape, a1, sep='\n')

## 방법1) reshape(), resize()
## -> resize() : 원본 적용 0, -1 사용 불가
a.resize(6)
print(a.shape, a, sep='\n')


(1, 3, 2)
[[[11 12]
  [13 14]
  [15 16]]]
(6,)
[11 12 13 14 15 16]
(6,)
[11 12 13 14 15 16]


In [ ]:
## 방법2) flatten()
## -> flatten() : 복사본 생성 후 1차원 변환. 속도가 상대적으로 느림
a = np.array([[[11,12], [13,14], [15,16]]])
print('원본 => ', a.shape, a, sep="\n")
print()

a1 = a.flatten()
print('1차원변형 => ', a1)
print()

a[0][0][0] = 77 
print('원본 a => ', a)
print('원본 a1 => ', a1)



원본 => 
(1, 3, 2)
[[[11 12]
  [13 14]
  [15 16]]]

1차원변형 =>  [11 12 13 14 15 16]

원본 a =>  [[[77 12]
  [13 14]
  [15 16]]]
원본 a1 =>  [11 12 13 14 15 16]


In [ ]:
## 방법3) revel()
## -> revel() : 원본 공유해서 1차원 변환
a = np.array([[[11,12], [13,14], [15,16]]])
print('원본 => ', a.shape, a, sep="\n")
print()

a1 = a.flatten()
print('1차원변형 => ', a1)
print()

a[0][0][0] = 77 
print('원본 a => ', a)
print('원본 a1 => ', a1)

