### [ 파일 입력과 출력 ]<hr>
- pandas.read_xxx() : 다양한 포맷의 파일 ==> dataFrame으로 변환
    * 파일 종류에 따라서 변환 시 설정 필요함

- pandas.to_xxx() : DataFrame ===> 다양한 포맷 str 또는 file로 변환

In [7]:
## [1] 모듈 로딩
import pandas as pd

In [ ]:
## -----------------------------------------------------
## [2] 데이터 준비 - 일반 csv 파일
## -----------------------------------------------------
FILE_NAME = '../Data/test_save.csv'

dataDF = pd.DataFrame([[10,20,30],
                      [11,21,31],
                      [12,22,32]], columns=['kor', 'eng', 'fra'])

display(dataDF)

## dataframe ===> csv파일러
dataDF.to_csv(FILE_NAME, index=False, sep="\t")

kor  eng  fra
0   10   20   30
1   11   21   31
2   12   22   32

In [19]:
## ---------------------------------------------
## dataframe의 다양한 형식 저장 : df.to_000()
## ---------------------------------------------
## df => numpy 저장
result = dataDF.to_numpy()
print(result)
## df => string 저장
result = dataDF.to_string()
print(type(result), result, sep='\n')

[[10 20 30]
 [11 21 31]
 [12 22 32]]
<class 'str'>
   kor  eng  fra
0   10   20   30
1   11   21   31
2   12   22   32


In [23]:
## kor 컬럼 선택
korSR  = dataDF['kor']
display(korSR)

## Series -> numpy
print(korSR.to_numpy())

## series => dataframe
korDF = korSR.to_frame()
display(korDF)


0    10
1    11
2    12
Name: kor, dtype: int64

[10 11 12]


kor
0   10
1   11
2   12

In [11]:
## [5] 데이터 준비 - 특정 컬럼을 행인덱스 설정
FILE_NAME = '../Data/test.csv'

## c0 컬럼을 행인덱스 설정
## index_col 매개변수 -> 1개 index_col = "컬럼명"
#                    -> 2개 index_col = ['컬럼명1', '컬럼명2']
csvDF = pd.read_csv(FILE_NAME, index_col='c0')

## 출력
csvDF

c1  c2  c3
c0            
10   9   8   3
78   4   7   2
6    2   9  12
7    8   9   3

In [12]:
## [6] 데이터 준비 - 일부 컬럼만 DataFrame으로 저장
FILE_NAME = '../Data/test.csv'

## 원하는 컬럼만 가져오기
## usescols 매개변수 -> usescols = ['컬럼명1', '컬럼명2']
##                  -> usescols = [정수, 정수]

csvDF = pd.read_csv(FILE_NAME, usecols=['c1', 'c2'])
csvDF2 = pd.read_csv(FILE_NAME, usecols=[1,2])


## 출력
display(csvDF, csvDF2, sep="\n\n")

c1  c2
0   9   8
1   4   7
2   2   9
3   8   9

c1  c2
0   9   8
1   4   7
2   2   9
3   8   9