##### [ 이미지 변형 - & ROI ]
- Numpy 방식 : 관심영역 설정
    * 픽셀의 값 범위 0 ~ 255로 제한 코드 직접 작성

- cv2 함수방식
    * cv2.add()/ substract()/ divistion()... : 내부에서 제한사항 처리

[1] 이미지 픽셀 기본 연산 <HR>

In [4]:
## 모듈 로딩
import numpy as np
import cv2
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [9]:
## 연산에 사용할 배열
a = np.uint8([[200,50]])
b = np.uint8([[100,100]])

## numpy 배열 직접 연산
add1 = a + b
sub1 = a - b
mult1 = a * 2
div1 = a / 3

## opencv api를 이용한 연산
add2 = cv2.add(a, b)
sub2 = cv2.subtract(a, b)
mult2 = cv2.multiply(a, 2)
div2 = cv2.divide(a, 3)

## 출력
print(add1, add2)
print(sub1, sub2)
print(mult1, mult2)
print(div1, div2)

[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[144 100]] [[255 100]]
[[66.66666667 16.66666667]] [[67 17]]
