#### [규제 layer - Dropout]
- 모델의 과대적합을 위한 규제 중
- 출력값에 지정된 비율(p)만큼 0으로 처리해 주는 층

[1] 모듈로딩 <hr>

In [19]:
## 모듈로딩
import torch
import torch.nn as nn


In [20]:
## 2개 layer 생성
fcLay = nn.Linear(4, 4)
dropLay = nn.Dropout(p=0.5)

##- 테스트용 텐서 생성
x = torch.randn(2,4)

print(x)


tensor([[ 0.0421, -1.4802,  2.2489, -0.7557],
        [ 0.0620, -0.5880, -0.5099,  1.1585]])


In [21]:
## 가중합 계산 + 활성화 함수
zTS = fcLay(x)
aTS = torch.relu(zTS)

print(f'zTS ==>\n{zTS} \n\n aTS===>\n{aTS}')

zTS ==>
tensor([[-1.6351,  1.2303, -0.2550, -0.5781],
        [-0.3863, -0.2201,  0.2665,  0.0110]], grad_fn=<AddmmBackward0>) 

 aTS===>
tensor([[0.0000, 1.2303, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2665, 0.0110]], grad_fn=<ReluBackward0>)


In [23]:
## [규제 Dropout] ---------------------------
## 일부 출력값 0 처리
## w도 없고, b도 없음
## 선형결과 (가중합)을 절대 하지 않음
## 이미 계산된 activation에 마스크만 곱함
## -----------------------------------------
outTS = dropLay(aTS)
print(f'aTS ==>\n{aTS} \n\n outTS===>\n{outTS}')


aTS ==>
tensor([[0.0000, 1.2303, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2665, 0.0110]], grad_fn=<ReluBackward0>) 

 outTS===>
tensor([[0.0000, 2.4605, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0220]], grad_fn=<MulBackward0>)


In [30]:
## ----------------------------------
## 학습중 :
## ----------------------------------

p = 0.2
mask = (torch.rand_like(aTS) > p).float()

print(f'mask\n{mask}')

outTS = aTS * mask / (1-p)
print(f'outTs\n{outTS}')

mask
tensor([[0., 1., 1., 0.],
        [0., 1., 1., 1.]])
outTs
tensor([[0.0000, 1.5378, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3331, 0.0137]], grad_fn=<DivBackward0>)


In [ ]:
## -----------------------
## 평가시 : 입력받은 tensor 그대로 출력
## -----------------------
outTS = aTS ## 아무것도 안함