#### 3-1-1. 이미자와 Numpy

In [1]:
#Opencv로 읽어들인 500 * 500 픽셀 이미지 정보를 담은 Numpy 배열의 속성정보 출력
import cv2
img = cv2.imread('../Data/Image/blank_500.jpg')
type(img)

numpy.ndarray

In [2]:
#ndarray = N-Dimensional Array(다차원 배열)
#이미지 = (행 x 열 x 채널)
#행, 열: 이미지의 크기(높이와 폭)
#채널: 컬러: 3개의 길이(파랑, 초록, 빨강)
#일반적으로 이미지를 읽었을 때 3차원 배열은 '높이 x 폭 x 3'의 형태이다.

print(img.ndim)
print(img.shape)
print(img.size)

3
(500, 500, 3)
750000


In [3]:
#Numpy는 수 많은 데이터를 처리해야 하므로 데이터 타입을 지정하는 것이 효과적이다.
#최대값이 255인 0 이상의 정수이면서 부호 없는 8비트 : uint8 데이터타입!!
print(img.dtype)
print(img.itemsize)

uint8
1


#### 3-1-2. Numpy 배열 생성

#### 3-1-3. 값으로 생성

In [4]:
import numpy as np
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
print(a.dtype)  #a: 리스트 항목이 모두 정수. int64로 자동 생성됨.
print(a.shape)

int64
(4,)


In [6]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  #b: 2차원 리스트 ==> (2, 4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
b.shape

(2, 4)

In [8]:
c = np.array([1, 2, 3.14, 4])  #c: 정수 + 소수점 있는 실수 ==> float.64
c

array([1.  , 2.  , 3.14, 4.  ])

In [9]:
c.dtype

dtype('float64')

In [10]:
d = np.array([1, 2, 3, 4], dtype = np.float32)  #d: float32 타입으로 명시.
d

#데이터 타입 명시할 경우 아래와 같이도 가능!
#a = np.uint8([1, 2, 3, 4])

array([1., 2., 3., 4.], dtype=float32)

#### 3-1-4. 크기와 초기값으로 생성

In [11]:
a = np.empty((2, 3))   #초기값이 제각각. a배열은 0에 가까운 수 6개로 이루어짐.
a

array([[4.24399158e-314, 2.81617418e-322, 6.95280008e-310],
       [0.00000000e+000, 6.23039694e-307, 2.22526399e-307]])

In [12]:
print(a.dtype)

float64


 - ndarray.fill(value): 배열의 모든 요소를 value로 채움.

In [13]:
a.fill(255)
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [14]:
#배열을 만들고 어떤 특정한 값으로 모든 요소를 초기화할 때: zeros(), ones(), full()
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
b.dtype                                #데이터타입 미지정: float64형.

dtype('float64')

In [16]:
c = np.zeros((2, 3), dtype = np.int8)   #데이터타입 지정.
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [17]:
d = np.ones((2, 3), dtype = np.int16)
d

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [18]:
e = np.full((2, 3, 4), 255, dtype = np.uint8)
e

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]], dtype=uint8)

In [19]:
img = cv2.imread('../Data/Image/girl.jpg')
img

array([[[ 52,  71,  76],
        [ 47,  68,  70],
        [ 39,  69,  64],
        ...,
        [ 24,  72,  54],
        [ 31,  76,  59],
        [ 35,  80,  63]],

       [[ 51,  70,  75],
        [ 47,  68,  70],
        [ 39,  69,  64],
        ...,
        [ 26,  74,  56],
        [ 32,  77,  60],
        [ 35,  80,  63]],

       [[ 51,  70,  73],
        [ 46,  67,  68],
        [ 39,  69,  64],
        ...,
        [ 28,  77,  57],
        [ 33,  78,  61],
        [ 35,  80,  63]],

       ...,

       [[ 29,  95,  66],
        [ 38, 104,  75],
        [ 47, 115,  84],
        ...,
        [218, 190, 203],
        [221, 191, 202],
        [222, 192, 203]],

       [[ 28,  94,  65],
        [ 37, 104,  75],
        [ 47, 117,  86],
        ...,
        [218, 190, 203],
        [222, 192, 203],
        [224, 194, 205]],

       [[ 25,  92,  63],
        [ 36, 103,  74],
        [ 46, 116,  85],
        ...,
        [223, 193, 206],
        [226, 196, 207],
        [229, 199, 210]]

In [20]:
img.shape

(293, 406, 3)

In [21]:
a = np.empty_like(img)
b = np.zeros_like(img)
c = np.ones_like(img)
d = np.full_like(img, 255)

In [22]:
print(a)
print(a.shape)

[[[192 186  95]
  [200  29   2]
  [  0   0 176]
  ...
  [ 71  38  82]
  [ 69  37  80]
  [ 65  33  72]]

 [[ 57  31  68]
  [ 52  24  60]
  [ 44  17  53]
  ...
  [ 72  38  82]
  [ 69  37  80]
  [ 65  35  74]]

 [[ 59  32  68]
  [ 54  25  61]
  [ 47  20  55]
  ...
  [ 70  40  85]
  [ 69  39  82]
  [ 67  37  77]]

 ...

 [[206 223 196]
  [206 224 197]
  [207 224 197]
  ...
  [207 228 196]
  [207 226 196]
  [207 227 197]]

 [[208 225 198]
  [208 225 198]
  [208 225 198]
  ...
  [208 229 197]
  [208 229 197]
  [208 228 198]]

 [[209 226 199]
  [209 225 198]
  [208 225 198]
  ...
  [209 229 197]
  [208 229 197]
  [208 227 197]]]
(293, 406, 3)


In [23]:
print(b)
print(b.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(293, 406, 3)


In [24]:
print(c)
print(c.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
(293, 406, 3)


In [25]:
print(d)
print(d.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
(293, 406, 3)


#### 3-1-5. 시퀀스와 난수로 생성

In [26]:
a = np.arange(5)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2 3 4]
int64
(5,)


In [27]:
#숫자 하나를 인자로 전달하면 0부터 시작하는 값을 순차적으로 갖는 1차원 배열 반환.
b = np.arange(5.0)
print(b)
print(b.dtype)
print(b.shape)

[0. 1. 2. 3. 4.]
float64
(5,)


In [28]:
#(시작값, 종료값, 증가폭)
c = np.arange(3, 9, 2)
c

array([3, 5, 7])

In [29]:
np.random.rand()

0.5591683140754107

In [30]:
np.random.randn()

-0.7271373988338049

In [31]:
#난수로 이루어진 배열
a = np.random.rand(2, 3)
a

array([[0.70714706, 0.42879862, 0.3363441 ],
       [0.40729848, 0.84315017, 0.53673619]])

In [32]:
b = np.random.randn(2, 3)
b

array([[-0.39426497,  1.17636848,  1.35784304],
       [ 0.30589922,  1.213695  , -0.23458266]])

In [33]:
#이미지 작업에 필요한 원하는 범위 내에서 난수를 발생하기 위해서는 브로드캐스팅, dtype변경이 필요한 경우가 많음.

#### 3-1-6. dtype 변경

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
a.dtype

dtype('int64')

In [36]:
#1. astype
b = a.astype('float32')
b

array([0., 1., 2., 3., 4.], dtype=float32)

In [37]:
c = a.astype(np.float64)
c, c.dtype

(array([0., 1., 2., 3., 4.]), dtype('float64'))

In [38]:
a.dtype

dtype('int64')

In [39]:
#2. uintXX(array), floatXX(array), complexXX(array)
d = np.uint8(a)    #
d

array([0, 1, 2, 3, 4], dtype=uint8)

#### 3-1-7. 차원 변경

In [40]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [41]:
b = a.reshape(2, 3) #a를 2행 3열로 바꾸는 작업.
b

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
c = np.reshape(a, (2, 3)) #a를 2행 3열로 바꾸는 작업2.
c

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
d = np.arange(100).reshape(2, -1) #-1 : 해당 차수는 크기를 지정하지 않겠으니, 나머지 차수를 이용해 알아서 계산하라.

In [44]:
e = np.arange(100).reshape(-1, 5)
e, e.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]),
 (20, 5))

In [45]:
#어떤 배열을 1차원으로 재정렬.
f = np.zeros((2, 3))
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
f.reshape((6,))

array([0., 0., 0., 0., 0., 0.])

In [47]:
f.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [48]:
np.ravel(f)

array([0., 0., 0., 0., 0., 0.])

In [49]:
#전치행렬
g = np.arange(10).reshape(2, -1)
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### 3-1-8. 브로드캐스팅 연산

In [51]:
#ex. 0부터 9까지 있는 파이썬 리스트의 모든 항목을 1씩 증가시키는 방법 비교.

#1. for문 사용
list1 = list(range(10))

for i in range(len(list1)):
    list1[i] = list1[i] + 1

print(list1)

#2. Numpy broadcasting 연산
import numpy as np
a = np.arange(10)
print(a + 1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
#numpy 배열과 scalar값 간의 여러가지 연산
print(a + 5)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

[ 5  6  7  8  9 10 11 12 13 14]
[-2 -1  0  1  2  3  4  5  6  7]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]


In [53]:
b = np.arange(6).reshape(2, -1)
print(b * 2)

[[ 0  2  4]
 [ 6  8 10]]


In [54]:
#비교연산도 가능.
#조건식 연산을 하면 True, False를 갖는 배열이 생성됨.
a > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [55]:
#배열 간 연산도 가능.
a = np.arange(10, 60, 10)
b = np.arange(1, 6)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a ** b)

[10 20 30 40 50]
[1 2 3 4 5]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[       10       400     27000   2560000 312500000]


In [56]:
#브로드캐스팅 불가한 경우.
a = np.ones((2, 3))
b = np.ones((3, 2))
# a + b

In [57]:
a = np.ones((2, 3))
c = np.arange(3)   #1차원이라도 열 개수가 a와 같으면 연산 가능.
print(a)
print(c)
print(a+c)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [58]:
#1차원 배열이라고 해도 열의 개수가 맞지 않으면 실패한다.
d = np.arange(2)
# a + d

In [59]:
#d의 모양을 바꾸면 열 단위 연산이 가능하다.
d = np.arange(2).reshape(2, 1)
print(d)
print(a+d)

[[0]
 [1]]
[[1. 1. 1.]
 [2. 2. 2.]]


#### 3-1-9.인덱싱과 슬라이싱

In [60]:
#인덱스로 각 요소에 접근하기.
#배열의 차원에 따라 인덱스의 개수도 달라짐.

a = np.arange(10)
print(a, a[5])

b = np.arange(12).reshape(3, 4)
print(b, b[1], b[1, 2])  #1개의 인덱스만 쓰면 1개 행 모두가 선택됨. 
                         #2개의 인덱스를 사용하여 열, 행 모두 지정해 주어야 1개의 요소만 선택됨.

[0 1 2 3 4 5 6 7 8 9] 5
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [4 5 6 7] 6


In [61]:
#값의 변경도 마찬가지. 인덱스를 하나만 지정하면 행 전체를 바꿔버린다.
print(a)
a[5] = 9
print(a)

print(b)
b[0] = 0
print(b)

b[1, 2] = 99
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 9 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  0  0  0]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  0  0  0]
 [ 4  5 99  7]
 [ 8  9 10 11]]


In [62]:
#인덱싱
a = np.arange(10)
print(a)

print(a[2:5])  #a[2], a[3], a[4]
print(a[5:])
print(a[:])

b = np.arange(12).reshape(3, 4)
print(b)
print(b[0:2, 1])
print(b[0:2, 1:3])
print(b[2, :])
print(b[:, 1])
b[0:2, 1:3] = 0
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 5]
[[1 2]
 [5 6]]
[ 8  9 10 11]
[1 5 9]
[[ 0  0  0  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]


In [63]:
#slicing의 결과는 복제본이 아닌 원본이다. 
#전체 배열 중 일부를 다른 변수에 할당할 때, 그것은 별도의 배열이 아니다.
#슬라이싱 해당 영역에 대한 참조일 뿐, 값의 변경은 원본에도 그대로 반영된다.
print(b)
bb = b[0:2, 1:3]
print()

print(bb)
bb[0] = 99
print()

print(b)

#복제본을 얻고싶다면 ndarray.copy()함수를 호출해야 함.
k = b.copy()
print(k)
k[0] = 7
print(k)
print(b)

[[ 0  0  0  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]

[[0 0]
 [0 0]]

[[ 0 99 99  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]
[[ 0 99 99  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]
[[ 7  7  7  7]
 [ 4  0  0  7]
 [ 8  9 10 11]]
[[ 0 99 99  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]


#### 3-1-10. 팬시 인덱싱

In [64]:
a = np.arange(5)
print(a)
print(a[[1, 3]])
print(a[[True, False, True, False, True]])

[0 1 2 3 4]
[1 3]
[0 2 4]


In [65]:
#Numpy 배열에 비교 연산 ==> 각 element가 조건을 만족하는지 알 수 있음.
#boolean이 든 배열을 인덱스처럼 사용하면 True값 위치의 value들만 얻을 수 있다.
a = np.arange(10)
print(a)
b = a >5
print(b)
print(a[b])
print(a[a>5])
a[a>5] = 1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]
[0 1 2 3 4 5 1 1 1 1]


In [66]:
#위의 경우도 새로운 값을 지정하면 브로드캐스팅 연산으로 해당 요소들 모두의 값을 바꿀 수 있음.
b = np.arange(12).reshape(3, 4)
print(b)
print(b[[0, 2]])
print(b[[0, 2], [2, 3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[ 2 11]


#### 3-1-11. 병합과 분리

In [67]:
a = np.arange(4).reshape(2, 2)
print(a)

b = np.arange(10, 14).reshape(2, 2)
print(b)

print(np.vstack((a, b)))
print(np.hstack((a, b)))
print(np.concatenate((a, b), 0))   #수직. axis = 0은 열 방향으로.
print(np.concatenate((a, b), 1))   #수평. axis = 1은 행 방향으로.

[[0 1]
 [2 3]]
[[10 11]
 [12 13]]
[[ 0  1]
 [ 2  3]
 [10 11]
 [12 13]]
[[ 0  1 10 11]
 [ 2  3 12 13]]
[[ 0  1]
 [ 2  3]
 [10 11]
 [12 13]]
[[ 0  1 10 11]
 [ 2  3 12 13]]


In [68]:
a = np.arange(12).reshape(4, 3)
b = np.arange(10, 130, 10).reshape(4, 3)
print(a)
print(b)

c = np.stack((a, b), 0)       #기존 (4, 3)에서 새로운 축이 1번째에 추가됨 => (2, 4, 3)
print(c.shape)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
(2, 4, 3)
[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]
  [100 110 120]]]


In [69]:
d = np.stack((a, b), 1)     #기존 (4, 3)에서 새로운 축이 1번째에 추가됨 => (4, 2, 3)
print(d.shape)
print(d)

e = np.stack((a, b), 2)     #기존 (4, 3)에서 새로운 축이 2번째에 추가됨 => (4, 3, 2)
print(e.shape)
print(e)

ee = np.stack((a, b), -1)   #기존 (4, 3)에서 새로운 축이 마지막 축 번호(2)에 추가됨 => (4, 2, 3)
print(ee.shape)
print(e)

(4, 2, 3)
[[[  0   1   2]
  [ 10  20  30]]

 [[  3   4   5]
  [ 40  50  60]]

 [[  6   7   8]
  [ 70  80  90]]

 [[  9  10  11]
  [100 110 120]]]
(4, 3, 2)
[[[  0  10]
  [  1  20]
  [  2  30]]

 [[  3  40]
  [  4  50]
  [  5  60]]

 [[  6  70]
  [  7  80]
  [  8  90]]

 [[  9 100]
  [ 10 110]
  [ 11 120]]]
(4, 3, 2)
[[[  0  10]
  [  1  20]
  [  2  30]]

 [[  3  40]
  [  4  50]
  [  5  60]]

 [[  6  70]
  [  7  80]
  [  8  90]]

 [[  9 100]
  [ 10 110]
  [ 11 120]]]


In [70]:
a = np.arange(12)              #a는 1차원 배열.
print(a)
print(np.hsplit(a, 3))         #배열을 3개로 쪼갠다.
print(np.hsplit(a, [3, 6]))    #3과 6을 배열로 표시. 즉 [0:3], [3:6], [6:]의 세 덩이로 나눈다.
print(np.hsplit(a, [3, 6, 9])) #3, 6, 9를 배열로 표시. [0:3], [3:6], [6:9], [9:]의 네 덩이로 나눈다.
print(np.split(a, 3, 0))       #a는 1차원이므로 축 번호는 0 뿐이다. hsplit(a, 3)과 결과 동일.
print(np.split(a, [3, 6, 9], 0)) #hsplit(a, [3, 6, 9])과 결과 동일.

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [71]:
b = np.arange(12).reshape(4, 3)   #b는 2차원 배열.
print(b)
print(np.vsplit(b, 2))            #4행짜리 배열을 2개로 쪼갠다.
print(np.split(b, 2, 0))          #vsplit(b, 2)과 결과 같음.
print(np.hsplit(b, [1]))          #3열짜리이므로 2로 나눌 순 없다. #[1] ==> [1:] #indice에 1을 주면 b와 똑같은 결과를 반환함.
print(np.split(b, [1], 1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])]
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])]


#### 3-1-12. 검색

In [72]:
#1차원 배열에서의 검색
a = np.arange(10, 20)
print(a)
print(np.where(a>15))         #조건에 맞는 인덱스를 배열로 반환.
print(np.where(a>15, 1, 0))   #기존 배열은 변경 X.
print(a)

[10 11 12 13 14 15 16 17 18 19]
(array([6, 7, 8, 9]),)
[0 0 0 0 0 0 1 1 1 1]
[10 11 12 13 14 15 16 17 18 19]


In [73]:
print(a)
print(np.where(a>15, 99, a)) #기존 배열은 변경 X.
print(np.where(a>15, a, 0))  #기존 배열은 변경 X.
print(a)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 99 99 99 99]
[ 0  0  0  0  0  0 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]


In [74]:
#다차원 배열에서의 검색
b = np.arange(12).reshape(3, 4)
print(b)

coords = np.where(b>6)
print(coords)          #수직으로 나눠진 1차원 배열 형태 2개를 반환. 행 번호와 열 번호가 따로 담긴 배열들.
print(np.stack((coords[0], coords[1]), -1))  #새로운 축(2차원)으로 배열 병합

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))
[[1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]]


In [75]:
#배열 중 0이 아닌 요소 찾기. 
#np.nonzero() ==> 0이 아닌 값이 있는 인덱스 반환.
z = np.array([0,1,2,0,1,2])
print(np.nonzero(z))

zz = np.array([[0,1,2], [1,2,0], [2,0,1]])
print(zz)

coords = np.nonzero(zz)
print(coords)

print(np.stack((coords[0], coords[1]), -1))

(array([1, 2, 4, 5]),)
[[0 1 2]
 [1 2 0]
 [2 0 1]]
(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))
[[0 1]
 [0 2]
 [1 0]
 [1 1]
 [2 0]
 [2 2]]


In [76]:
#nonzero()함수는 Trur, False의 boolean값에 대해서는 False를0으로 간주함.
#이를 이용해, numpy.where()함수처럼 조건을 만족하는 요소의 인덱스를 찾을 수도 있음.
print(a)
print(np.nonzero(a>15))
print(np.where(a>15))
print()
print(b)
print(np.nonzero(b>6))

[10 11 12 13 14 15 16 17 18 19]
(array([6, 7, 8, 9]),)
(array([6, 7, 8, 9]),)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))


In [77]:
#all(): 배열의 모든 요소가 참 또는 거짓인지 확인.
t = np.array([True, True, True])
print(np.all(t))
t[1] = False
print(t)
print(np.all(t))   #한 원소라도 거짓이면 False

True
[ True False  True]
False


In [78]:
tt = np.array([[True, True], [False, True], [True, True]])
print(tt)
print(np.all(tt, 0))   #축 인자(0, 1)를 지정하면 해당 축을 기준으로 True를 만족하는지 반환함.
print(np.all(tt, 1))

[[ True  True]
 [False  True]
 [ True  True]]
[False  True]
[ True False  True]


In [79]:
#numpy.all()과 numpy.where()를 이용하여 2개의 배열이 서로 같은지 다른지, 어느 항목이 다른지 찾을 수 있음.

a = np.arange(10)
b = np.arange(10)
print(a)
print(b)
print(a==b)
print(np.all(a==b))

b[5] = -1
print(a)
print(b)

print(np.all(a==b))      #서로 같은 값으로 채워졌는지 확인.  #배열에 들어있는 값 뿐만 아니라 순서까지 같아야 True.
print(np.where(a==b))    #인덱스 반환
print(np.where(a!=b))    #인덱스 반환

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True  True  True  True  True  True]
True
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 -1  6  7  8  9]
False
(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)
(array([5]),)


#### 3-1-13. 기초통계함수

In [80]:
a = np.arange(12).reshape(3, 4)
print(a)
print(np.sum(a))
print(np.sum(a, 0))
print(np.sum(a, 1))

print(np.amin is np.min)
print(np.amax is np.max)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
False
False


#### 3-1-14. 이미지 생성

In [ ]:
#practice. Numpy 배열로 체크무늬 그레이 스케일 이미지 생성
                                               #OpenCV에서 이미지를 표현하기 위한 Numpy 배열은 반드시 dtype = uint8.
                                               #0은 검은색, 255는 흰색
img = np.zeros((120, 120), dtype = np.uint8)   #120 x 120 2차원 배열 생성, 검은색 흑백 이미지
img[25:35, :] = 45                             #25 ~ 35행 모든 열에 45 할당
img[55:65, :] = 115                            #55 ~ 65행 모든 열에 115 할당
img[85:95, :] = 160                            #85 ~ 95행 모든 열에 160 할당
img[:, 35:45] = 205                            #35 ~ 45열 모든 행에 205 할당
img[:, 75:85] = 255                            #75 ~ 85열 모든 행에 255 할당
cv2.imshow('Gray', img)                        
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#practice. Numpy 배열로 체크무늬 BGR 스케일 이미지 생성
import cv2
import numpy as np

img = np.zeros((120, 120, 3), dtype = np.uint8)  #120 x 120 3채널의 3차원 배열 생성, 컬러 이미지
img[25:35, :] = [255, 0, 0]                      #25 ~ 35행 모든 열에 [255, 0, 0] 할당  #Blue
img[55:65, :] = [0, 255, 0]                      #55 ~ 65행 모든 열에 [0, 255, 0] 할당  #Green
img[85:95, :] = [0, 0, 255]                      #85 ~ 95행 모든 열에 [0, 0, 255] 할당  #Red
img[:, 35:45] = [255, 255, 0]                    #35 ~ 45열 모든 행에 [255, 255, 0] 할당  #Sky
img[:, 75:85] = [255, 0, 255]                    #75 ~ 85열 모든 행에 [255, 0, 255] 할당  #Pink

cv2.imshow('Gray', img)                        
cv2.waitKey(0)
cv2.destroyAllWindows()